version: '3.8'

services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    command: 
      - "--requirepass=${DRAGONFLY_PASSWORD}"
      - "--default_lua_flags=allow-undeclared-keys"
      - "--lock_on_hashtags"
      - "--cluster_mode=emulated"
    volumes:
      - dragonfly-data:/data
    networks:
      - coolify
      - public

  firecrawl-api:
    build:
      context: .  # Build from repo root
      dockerfile: apps/api/Dockerfile-coolify
    environment:
      - PORT=3002
      - REDIS_URL=redis://:${DRAGONFLY_PASSWORD}@dragonfly:6379
      - REDIS_RATE_LIMIT_URL=redis://:${DRAGONFLY_PASSWORD}@dragonfly:6379
      - PLAYWRIGHT_MICROSERVICE_URL=http://playwright-service:3000/html
      - NUM_WORKERS_PER_QUEUE=8
      - BULL_AUTH_KEY=${BULL_AUTH_KEY}
      - BULL_PREFIX_QUEUE="{scrapeQueue}"  # Enables hashtag grouping
      - JOB_TIMEOUT=120000  # 120 seconds
      - REQUEST_TIMEOUT=90000  # 90 seconds

    networks:
      - coolify
    ports:
      - "3002:3002"
    depends_on:
      - dragonfly
      - playwright-service

  firecrawl-worker:
    build:
      context: apps/api  # Same as API service
      dockerfile: Dockerfile-coolify
    environment:
      - REDIS_URL=redis://:${DRAGONFLY_PASSWORD}@dragonfly:6379
      - REDIS_RATE_LIMIT_URL=redis://:${DRAGONFLY_PASSWORD}@dragonfly:6379
      - PLAYWRIGHT_MICROSERVICE_URL=http://playwright-service:3000/html
      - WORKER_TIMEOUT=180000  # 3 minutes
    networks:
      - coolify
      
    depends_on:
      - firecrawl-api

  playwright-service:
    build: 
      context: apps/playwright-service-ts
    environment:
      - PORT=3000
      - HEADLESS=true
    networks:
      - coolify
    volumes:
      - playwright-storage:/ms-playwright

volumes:
  dragonfly-data:
  playwright-storage:

networks:
  coolify:
    external: true
    attachable: true
  public:
    driver: bridge
